version: '3.1'

services:
  php:
    build:
      context: ./docker/php/8.2
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - .:/var/www/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
